import prisma from '../prisma/client';
import { PortfolioSnapshotDTO } from '../types/portfolio';
import { PortfolioHistoryPoint, SaveSnapshotInput, SnapshotRecord } from '../types/snapshot';

export class SnapshotService {
  /**
   * Persists a single portfolio snapshot record into Prisma.
   * Validation is intentionally kept here so the service remains reusable in tests and background jobs.
   */
  async saveSnapshot(input: PortfolioSnapshotDTO & { brokerAccountId: string; dailyPnl: number; snapshotDate?: Date }): Promise<SnapshotRecord> {
    if (!input.brokerAccountId) {
      throw new Error('brokerAccountId is required');
    }

    const snapshotDate = input.snapshotDate ?? new Date();

    const snapshot = await prisma.portfolioSnapshot.create({
      data: {
        portfolioValue: Number(input.portfolioValue),
        investedValue: Number(input.investedValue),
        totalPnl: Number(input.totalPnl),
        dailyPnl: Number(input.dailyPnl ?? 0),
        snapshotDate,
        brokerAccountId: input.brokerAccountId,
      },
    });

    return {
      id: snapshot.id,
      portfolioValue: snapshot.portfolioValue,
      investedValue: snapshot.investedValue,
      totalPnl: snapshot.totalPnl,
      dailyPnl: snapshot.dailyPnl,
      snapshotDate: snapshot.snapshotDate,
      brokerAccountId: snapshot.brokerAccountId,
    };
  }

  /**
   * Convenience method for the scheduled daily flow.
   * It takes the portfolio snapshot DTO generated by PortfolioService and persists it with the broker account context.
   */
  async saveDailySnapshot(input: SaveSnapshotInput): Promise<SnapshotRecord> {
    return this.saveSnapshot({
      portfolioValue: input.portfolioValue,
      investedValue: input.investedValue,
      totalPnl: input.totalPnl,
      generatedAt: input.snapshotDate,
      brokerAccountId: input.brokerAccountId,
      dailyPnl: input.dailyPnl,
      snapshotDate: input.snapshotDate,
    });
  }

  /**
   * Retrieves the historical portfolio values for a broker account in a date range.
   * This is suitable for analytics charts and trend reporting.
   */
  async getPortfolioHistory(
    brokerAccountId: string,
    startDate: Date,
    endDate: Date,
  ): Promise<PortfolioHistoryPoint[]> {
    const snapshots = await prisma.portfolioSnapshot.findMany({
      where: {
        brokerAccountId,
        snapshotDate: {
          gte: startDate,
          lte: endDate,
        },
      },
      orderBy: {
        snapshotDate: 'asc',
      },
      select: {
        snapshotDate: true,
        portfolioValue: true,
        investedValue: true,
        totalPnl: true,
      },
    });

    return snapshots.map((snapshot) => ({
      snapshotDate: snapshot.snapshotDate,
      portfolioValue: snapshot.portfolioValue,
      investedValue: snapshot.investedValue,
      totalPnl: snapshot.totalPnl,
    }));
  }
  async getLatestSnapshot(
    userId: string
  ) {
    return prisma.portfolioSnapshot.findFirst({
      where: {
        brokerAccount: {
          userId,
        },
      },

      orderBy: {
        snapshotDate: 'desc',
      },
    });
  }
}
